// for home page


export const ALL_PRODUCT_REQUEST = "PRODUCT_DETAILS_REQUESTS";
export const ALL_PRODUCT_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const ALL_PRODUCT_FAIL = "PRODUCT_DETAILS_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";

// for single product detail

export const PRODUCT_DETAILS_REQUESTS = "PRODUCT_DETAILS_REQUESTS";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";


export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUESTS";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";
